services:

  db:
    image: postgres:14
    restart: always
    container_name: database
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - .:/docker-entrypoint-initdb.d

  etl:
    build: ./
    container_name: datafarm_etl
    command: ["python3", "main.py"]
    restart: always
    volumes:
      - .:/app
    env_file:
      - ./.env