version: "3"

services:
  datafarm:
    build: ./
    container_name: etl
    command: ["python3", "main.py"]
    volumes:
      - .:/app
    env_file:
      - ./.env

  db:
    image: postgres:14
    restart: always
    container_name: database
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - .:/docker-entrypoint-initdb.d