version: "3"

services:
  datafarm:
    build: ./
    container_name: datafarm_etl
    command: ["python3", "main.py"]
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env

  db:
    image: postgres:14
    restart: always
    container_name: datafarm_database
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - .:/docker-entrypoint-initdb.d